// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    MessageApi: typeof import('./src/components/message-api.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
